name: segysak

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - dask
  - dask-core
  - distributed
  - numpy
  - pandas
  - xarray
  - toolz
  - tqdm
  - scipy
  - pyvista
  - ipython
  - ipykernel
  - jupyter
  - ipywidgets
  - nbconvert
  - jupytext
  - segyio
  - matplotlib
  - pip
  - click
  - attrdict
  - pyshp
  - pip:
      - sphinxcontrib-programoutput
      - sphinx-copybutton
      - nbsphinx >= 0.7
      - pandoc
      - h5netcdf>=0.8
      - parso<0.8.0,>=0.7.0
      - rtds-action
