name: segysak

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - tqdm
  - jupytext
  - segyio
  - pip
  - click
  - addict
  - matplotlib
  - pypandoc
  - pip:
      - sphinxcontrib-programoutput
      - sphinx-copybutton
      - nbsphinx >= 0.7
      - pandoc
      - parso<0.8.0,>=0.7.0
      - rtds-action
      - pyzgy
